// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"

	service "multiplica/internal/service"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MultiplyServiceClient is the client API for MultiplyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MultiplyServiceClient interface {
	Multiply(ctx context.Context, in *MultiplyRequest, opts ...grpc.CallOption) (*MultiplyResponse, error)
}

type multiplyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMultiplyServiceClient(cc grpc.ClientConnInterface) MultiplyServiceClient {
	return &multiplyServiceClient{cc}
}

func (c *multiplyServiceClient) Multiply(ctx context.Context, in *MultiplyRequest, opts ...grpc.CallOption) (*MultiplyResponse, error) {
	out := new(MultiplyResponse)
	err := c.cc.Invoke(ctx, "/grpc.MultiplyService/Multiply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MultiplyServiceServer is the server API for MultiplyService service.
// All implementations must embed UnimplementedMultiplyServiceServer
// for forward compatibility
type MultiplyServiceServer interface {
	Multiply(context.Context, *MultiplyRequest) (*MultiplyResponse, error)
}

type MultiplyGrpcServer struct {
}

func (MultiplyGrpcServer) Multiply(ctx context.Context, req *MultiplyRequest) (*MultiplyResponse, error) {
	r := service.Multiply(req.NumberA, req.NumberB)
	resp:= MultiplyResponse{Result: r}
	return &resp, nil
}

// UnsafeMultiplyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MultiplyServiceServer will
// result in compilation errors.
type UnsafeMultiplyServiceServer interface {
	mustEmbedUnimplementedMultiplyServiceServer()
}

func RegisterMultiplyServiceServer(s grpc.ServiceRegistrar, srv MultiplyServiceServer) {
	s.RegisterService(&MultiplyService_ServiceDesc, srv)
}

func _MultiplyService_Multiply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiplyServiceServer).Multiply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.MultiplyService/Multiply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiplyServiceServer).Multiply(ctx, req.(*MultiplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MultiplyService_ServiceDesc is the grpc.ServiceDesc for MultiplyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MultiplyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.MultiplyService",
	HandlerType: (*MultiplyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Multiply",
			Handler:    _MultiplyService_Multiply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/multiply.proto",
}
